import BaseConfigProvider from "@/context/BaseConfigProvider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "primeicons/primeicons.css";
import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/mdc-light-deeppurple/theme.css";
import { Suspense } from "react";
import "./globals.scss";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Noche de alitas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es'>
      <head>
        <meta httpEquiv='Content-Language' content='es' />
        {/* <meta name="google" content="notranslate" /> */}
        <meta name='theme-color' content='#317EFB' />
        <meta name='apple-mobile-web-app-status-bar-style' content='black' />
        <meta name='mobile-web-app-capable' content='yes' />
        <script src='https://kit.fontawesome.com/49a17ce65c.js' crossOrigin='anonymous' async />
      </head>
      <body
        className={cn(
          roboto.variable,
          "antialiased flex flex-col justify-center p-0 m-0 min-h-screen "
        )}>
        <div
          id='simulateTouchElement'
          tabIndex={-1}
          style={{
            position: "absolute",
            top: "-1000px",
            left: "-1000px",
            width: "1px",
            height: "1px",
            opacity: 0,
            pointerEvents: "none",
          }}
        />
        <Suspense fallback={<div>Cargando...</div>}>
          <BaseConfigProvider>{children}</BaseConfigProvider>
      </Suspense>
      </body>
    </html>
  );
}
